// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppBlock: typeof import('./components/app-block.vue')['default']
    AppBook: typeof import('./components/app-book.vue')['default']
    AppBooks: typeof import('./components/app-books.vue')['default']
    AppButton: typeof import('./components/app-button.vue')['default']
    AppProfile: typeof import('./components/app-profile.vue')['default']
    AppRecomendation: typeof import('./components/app-recomendation.vue')['default']
    AppTitle: typeof import('./components/app-title.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    'IconCarbon:favorite': typeof import('~icons/carbon/favorite')['default']
  }
}

export { }
