// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppBlock: typeof import('./components/app-block.vue')['default']
    AppBook: typeof import('./components/app-book.vue')['default']
    AppBookEditable: typeof import('./components/app-book-editable.vue')['default']
    AppBookEditableEntry: typeof import('./components/app-book-editable-entry.vue')['default']
    AppBooks: typeof import('./components/app-books.vue')['default']
    AppButton: typeof import('./components/app-button.vue')['default']
    AppProfile: typeof import('./components/app-profile.vue')['default']
    AppRecommendation: typeof import('./components/app-recommendation.vue')['default']
    AppTitle: typeof import('./components/app-title.vue')['default']
    BookPageWrap: typeof import('./components/book-page-wrap.vue')['default']
    'IconCarbon:add': typeof import('~icons/carbon/add')['default']
    'IconCarbon:close': typeof import('~icons/carbon/close')['default']
    'IconCarbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
  }
}

export { }
