// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/app-button.vue')['default']
    AppTitle: typeof import('./components/app-title.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    'IconCarbon:favorite': typeof import('~icons/carbon/favorite')['default']
  }
}

export { }
